# Exclude all build paths
builds/
# But dont exclude the produced binary files (so buildfiles will not get synchronized reducing overhead)
!builds/*/x_bookmark_manager*

# Exclude external/
external/
# But dont exclude the submodule external/pdf 
!external/pdf/
# But build-windows will be excluded in the submodule
external/pdf/build-windows/
