# Github Path is the repo, for the pull on the build targets@host
local       | posix   |                        |                               |          |     |
windows     | cmd     | machine1@192.168.0.200 | C:/Users/win/Desktop/project  | password | https://github.com/vi0lin/project.git |
wsl         | wsl     | machine1@192.168.0.200 | /home/machine/Desktop/project | password | https://github.com/vi0lin/project.git |
linux       | posix   | linuxuser@linuxhost | /home/linuxuser/project          |          | https://github.com/vi0lin/project.git |
buildserver | posix   | user@192.168.0.160  | /home/user/project               |          | https://github.com/vi0lin/project.git |
