declare -A CONF_CMD BUILD_CMD REQUIRE RUN_CMD PUBLISH_CMD INSTALL_CMD DOWNLOAD RELEASE_NAME

RELEASE_NAME[deb]=linux
RELEASE_NAME[deb-asan]=linux-debug
RELEASE_NAME[exe]=windows
RELEASE_NAME[apk]=android

CONF_CMD[deb]='cmake -B builds/deb -S . -G Ninja -DCMAKE_BUILD_TYPE=Release'
BUILD_CMD[deb]='cmake --build builds/deb -j ${JOBS}'
RUN_CMD[deb]='./builds/deb/x_bookmark_manager'
PUBLISH_CMD[deb]='./publish_release.sh builds/deb'
DOWNLOAD[deb]='builds/deb/x_bookmark_manager'

CONF_CMD[deb-asan]='cmake -B builds/deb-asan -S . -G Ninja -DXBM_SANITIZE=ON -DCMAKE_BUILD_TYPE=Debug'
BUILD_CMD[deb-asan]='cmake --build builds/deb-asan'
RUN_CMD[deb-asan]='ASAN_OPTIONS=detect_leaks=0:abort_on_error=1 ./builds/deb-asan/x_bookmark_manager'
PUBLISH_CMD[deb-asan]='./publish_release.sh builds/deb-asan'
DOWNLOAD[deb-asan]='builds/deb-asan/x_bookmark_manager'

CONF_CMD[exe]='cmake -B builds/exe -S . -G Ninja -DCMAKE_BUILD_TYPE=Release'
BUILD_CMD[exe]='cmake --build builds/exe -j ${JOBS}'
RUN_CMD[exe]='./builds/exe/x_bookmark_manager.exe'
PUBLISH_CMD[exe]='./publish_release.sh builds/exe'
DOWNLOAD[exe]='builds/exe/x_bookmark_manager.exe'

CONF_CMD[apk]='true'
BUILD_CMD[apk]='./build_apk.sh'
RUN_CMD[apk@windows]='cd /mnt/c/Users/win/Desktop/x && adb.exe uninstall com.mrtn.xbookmarkmanager; adb.exe install ./android/x_bookmark_manager.apk; adb.exe shell am start -n com.mrtn.xbookmarkmanager/.XbmActivity;'
PUBLISH_CMD[apk]='./publish_release.sh android'
DOWNLOAD[apk]='android/x_bookmark_manager.apk'
